### ISSUE TITLE
project does not pass compiling on openSUSE leap 42.1

### ISSUE THREAD

**Issue by colyli** [Seagate/h-flat#5] opened 2016-06-28 06:53 UTC
It seems this project does not pass compiling on newer Linux distribution, the depended google projects also have some symbol changes but h-flat project does not follow up. I try to spend whole day to fix the compiling errors, but I am not familiar with C++, finally lost myself on some libraries or symbol dependences.

Is it possible for maintainers to update the project, to make project pass compiling on newer Linux distribution ?

Thanks.

**Comment by plensing** [comment] 2016-06-28 08:16
Hello,

thanks for the heads-up. It looks like there are problems when compiling the kinetic-cpp-client library that the h-flat project depends on. I am currently on vacation, I will fix the automatic compilation next Tuesday (July 5th). 

If you don't want to wait a week you can try the following work-around:
I wrote an alternative build script for the kinetic-cpp-client that is available at: https://github.com/plensing/kinetic-cpp-client . Try to build the fork. You can either previously install glog and gflags on your system or use the "cmake -DGOOGLE_STATIC=on" flag to attempt building them automatically. If it builds for you, modify the KINETIC_CLIENT_PATH variable in the hflat CMakeLists.txt file to point to the your cpp-client directory. 

Sorry for the inconvenience. Hope this helps you.

**Comment by plensing** [comment] 2016-07-05 23:21
I have modified the build process (and description). Please let me know if everything works for you or if you are still encountering problems.

**Comment by plensing** [comment] 2016-07-19 18:13
I assume the problem is resolved and will close the issue. Feel free to re-open if you are still encountering problems.

**Closed by plensing** 2016-07-19 18:13 UTC
